services:
  monogs:
    build: .
    image: monogs
    environment:
      - DISPLAY=host.docker.internal:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - datasets:/MonoGS/datasets      # So the datasets persist between sessions
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
      - /usr/lib/wsl:/usr/lib/wsl      # For WSL2 NVIDIA driver access      
    command: bash
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  datasets:
