version: '3.8'
services:
  monogs:
    build: .
    image: monogs
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - datasets:/MonoGS/datasets
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  datasets:
